### PR TITLE
Created TripletSum in Algorithms/GeneralAlgorithms

### LINKED ISSUE #73: Add TripletSum Algorithm
Add TripletSum Algorith, under Algorithm/General_Algorithm.

### PR DESCRIPTION
**Pull request by Kush1101**
The solution involves a naive as well as an optimized implementation and uses the timeit library to compare both the implementations. All functions have docstrings, doctests and clean readable code.
Closes #73

### CODE REVIEW

**Comment by Apoorve73** [comment]
Comment on Issue #73 and mention it in the PR Description!

**Comment by Kush1101** [comment]
What was the point of opening an issue after I made the PR

**Comment by Apoorve73** [comment]
> What was the point of opening an issue after I made the PR

We are soon going to divide the repo into a trio, and are maintaining it, therefore, it is equally necessary to follow the best practices. 

**A PR can only be accepted if it refers to some opened issue!**

*Hope you get that! :smiley_cat: !*
Great Work! :clap:

**Comment by Apoorve73** [comment]
Refers #72

**Comment by Kush1101** [comment]
> > What was the point of opening an issue after I made the PR
> 
> We are soon going to divide the repo into a trio, and are maintaining it, therefore, it is equally necessary to follow the best practices.
> 
> **A PR can only be accepted if it refers to some opened issue!**
> 
> _Hope you get that! 😺 !_
> Great Work! 👏

You could have done that from later on. Because of that open issue, many people submitted PR's unnecessarily.

**Comment by Apoorve73** [comment]
Thank you for your opinion.
@Kush1101 🌟

**Comment by Kush1101** [comment]
You're welcome.

**Pull request merged**
