### PR TITLE
WIP Update readme.md

### PR DESCRIPTION
**Pull request by DamianArado**
added all the relevant infos.

### CODE REVIEW

**Comment by sanjana-302** [comment]
@DamianArado Nice to see you here! Great work!
As the issue mentioned you need to specify contributing guidelines also.
Add more relevant information like: link to repository , use proper markdown.

**Comment by Apoorve73** [comment]
@DamianArado, use semantic naming while making a Pull request.

**Comment by DamianArado** [comment]
Wrote almost everything that i seemed was relevant for any beginner. Suggestions are welcome.

**Comment by Apoorve73** [comment]
Great Work @DamianArado . Your Pull request shall be merged when other repository maintainers review your changes!

**Comment by Apoorve73** [comment]
@sanjana-302  and @maaz-bin-asad , kindly review the changes and suggest changes, if any.

**Comment by maaz-bin-asad** [comment]
@Apoorve73 It looks completely fine to me

**Comment by sanjana-302** [comment]
Looks fine to me. We need to still edit some portions. For now we can merge. I will keep updating. 👍

**Comment by Apoorve73** [comment]
I will merge the PR with a WIP tag then!

**Comment by maaz-bin-asad** [comment]
Okay

**Pull request merged**
